### ISSUE TITLE
Installation instructions direct user to clone from PNNL GitLab

### ISSUE THREAD

**Issue by abdelrahman-ayad** [pnnl/ExaGO#116]
**Issue type**
- [ ] New feature
- [ ] Bug
- [ ] Discussion
- [x] Other

**Relates to**
- [ ] OPFLOW
- [ ] SOPFLOW
- [ ] SCOPFLOW
- [ ] TCOPFLOW
- [ ] CMake build system
- [ ] Spack configuration
- [x] Manual
- [ ] Web docs
- [ ] Other

**Summary**

Cloning the repo requires a GitLab account (via Https). 

**Exact commands to reproduce, if applicable**

git clone https://gitlab.pnnl.gov/exasgd/frameworks/exago.git

**Relevant logs and/or screenshots, if applicable**
git clone https://gitlab.pnnl.gov/exasgd/frameworks/exago.git exago
Cloning into 'exago'...
Username for 'https://gitlab.pnnl.gov':

**Comment by pelesh** [comment]
This is documentation bug in installation [instructions](https://github.com/pnnl/ExaGO/blob/develop/INSTALL.md#acquiring-the-source-code). Instead use:
```
git clone https://github.com/pnnl/ExaGO.git
```

**Comment by abdelrahman-ayad** [comment]
That works, thank you!

**Comment by abhyshr** [comment]
`A required submodule was not downloaded! GIT_SUBMODULE was turned off or
  failed.  Please update submodules and try again.
Call Stack (most recent call first):
  CMakeLists.txt:42 (include)`

-- Also, this is the error that he's getting.

**Comment by abhyshr** [comment]
Hello @abdelrahman-ayad : Please see the updated instructions on the [install page](https://github.com/pnnl/ExaGO/blob/develop/INSTALL.md)
