### ISSUE TITLE
Jupyter Notebook Support / Python API additions

### ISSUE THREAD

**Issue by cameronrutherford** [pnnl/ExaGO#35]
For future ExaGO documentation, having `.ipynb` files available for reference is important. In addition, @abhyshr has discussed the desire to post-process ExaGO data in Python, which might require API changes.

To resolve the issue:
- [x] Create basic Jupyter notebook without MPI running OPFLOW example
- [x] Write OPFLOW output to disk with `saveSolution`, and then read that back into Python staying in JSON (maybe convert to dict...)
- [ ] Add Python function that returns a dictionary of the OPFLOW output without needing to read/write to disk

These activities should be considered in the context of #32, as Jupyter notebooks are easy to render and document alongside Quarto.

**Comment by cameronrutherford** [comment]
https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/ - we should render #32 Quarto docs for our project in GitHub actions, and then use our exago spack version to generate our docs.

**Comment by cameronrutherford** [comment]
Would be great to add a notebook/configuration to compare linear solvers using MA57, ReSolve and ReSolve GPU as backend to Ipopt. cc @pelesh

**Comment by cameronrutherford** [comment]
Is it possible to run mpi4py within Jupyter? https://github.com/mpi4py/mpi4py/discussions/294

If so, lets get that working for a demo!

If not, need to resolve #16

**Comment by cameronrutherford** [comment]
@abhyshr  and @jaelynlitz can we close this out? Maybe we can make a new issue that better summarizes remaining work?

#85 made me realize we have closed out Jupyter and base example side of things, but it might be easier to just consolidate and move python API side of things to new issue since different end users might have different needs and ways to connect there data outputs...

**Comment by abhyshr** [comment]
Good to close. We already have Jupyter notebooks in develop now.
