### ISSUE TITLE
OPFLOW HiOp functionality tests failing with `hiop@1.0.0`

### ISSUE THREAD

**Issue by cameronrutherford** [pnnl/ExaGO#43]
From GitLab, this was happening on Newell, Deception and Incline - https://gitlab.pnnl.gov/exasgd/frameworks/exago/-/issues/469

Now is is also happening on Ascent in #20 - https://code.ornl.gov/ecpcitest/exasgd/exago/-/jobs/2072667

These tests are skipped through a labels in `tests/functionality/opflow/CMakeLists.txt`

**Comment by jaelynlitz** [comment]
now fixed on Newell in #84

**Comment by jaelynlitz** [comment]
now fixed on Deception in #84 https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/138063

**Comment by cameronrutherford** [comment]
Incline and Ascent next ;)

What about similar tests in #3?

**Comment by jaelynlitz** [comment]
enabling to find out...

**Comment by jaelynlitz** [comment]
Incline's sole OPFLOW failure is a seg fault on test `FUNCTIONALITY_TEST_OPFLOW_RAJAHIOP_SPARSE_GPU_TOML_TESTSUITE` 

https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/138118#L108

**Comment by cameronrutherford** [comment]
> Incline's sole OPFLOW failure is a seg fault on test `FUNCTIONALITY_TEST_OPFLOW_RAJAHIOP_SPARSE_GPU_TOML_TESTSUITE`
> 
> https://gitlab.pnnl.gov/exasgd/frameworks/exago-github-mirror/-/jobs/138118#L108

Sounds like you can disable that test on incline, and create new PR since test failure is isolated. Would be worth checking for identical behavior on Crusher (using #34 or otherwise), and making sure to use older ROCm version to match incline (unlike #89)
